//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vndToForegin", ReplyAction="*")]
        WebApplication1.ServiceReference1.vndToForeginResponse vndToForegin(WebApplication1.ServiceReference1.vndToForeginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vndToForegin", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.vndToForeginResponse> vndToForeginAsync(WebApplication1.ServiceReference1.vndToForeginRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/foreginToVND", ReplyAction="*")]
        WebApplication1.ServiceReference1.foreginToVNDResponse foreginToVND(WebApplication1.ServiceReference1.foreginToVNDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/foreginToVND", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.foreginToVNDResponse> foreginToVNDAsync(WebApplication1.ServiceReference1.foreginToVNDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class vndToForeginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="vndToForegin", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.vndToForeginRequestBody Body;
        
        public vndToForeginRequest() {
        }
        
        public vndToForeginRequest(WebApplication1.ServiceReference1.vndToForeginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class vndToForeginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double vnd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        public vndToForeginRequestBody() {
        }
        
        public vndToForeginRequestBody(double vnd, string name) {
            this.vnd = vnd;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class vndToForeginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="vndToForeginResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.vndToForeginResponseBody Body;
        
        public vndToForeginResponse() {
        }
        
        public vndToForeginResponse(WebApplication1.ServiceReference1.vndToForeginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class vndToForeginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double vndToForeginResult;
        
        public vndToForeginResponseBody() {
        }
        
        public vndToForeginResponseBody(double vndToForeginResult) {
            this.vndToForeginResult = vndToForeginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class foreginToVNDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="foreginToVND", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.foreginToVNDRequestBody Body;
        
        public foreginToVNDRequest() {
        }
        
        public foreginToVNDRequest(WebApplication1.ServiceReference1.foreginToVNDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class foreginToVNDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double foregin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        public foreginToVNDRequestBody() {
        }
        
        public foreginToVNDRequestBody(double foregin, string name) {
            this.foregin = foregin;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class foreginToVNDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="foreginToVNDResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.foreginToVNDResponseBody Body;
        
        public foreginToVNDResponse() {
        }
        
        public foreginToVNDResponse(WebApplication1.ServiceReference1.foreginToVNDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class foreginToVNDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double foreginToVNDResult;
        
        public foreginToVNDResponseBody() {
        }
        
        public foreginToVNDResponseBody(double foreginToVNDResult) {
            this.foreginToVNDResult = foreginToVNDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.WebService1Soap>, WebApplication1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.vndToForeginResponse WebApplication1.ServiceReference1.WebService1Soap.vndToForegin(WebApplication1.ServiceReference1.vndToForeginRequest request) {
            return base.Channel.vndToForegin(request);
        }
        
        public double vndToForegin(double vnd, string name) {
            WebApplication1.ServiceReference1.vndToForeginRequest inValue = new WebApplication1.ServiceReference1.vndToForeginRequest();
            inValue.Body = new WebApplication1.ServiceReference1.vndToForeginRequestBody();
            inValue.Body.vnd = vnd;
            inValue.Body.name = name;
            WebApplication1.ServiceReference1.vndToForeginResponse retVal = ((WebApplication1.ServiceReference1.WebService1Soap)(this)).vndToForegin(inValue);
            return retVal.Body.vndToForeginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.vndToForeginResponse> WebApplication1.ServiceReference1.WebService1Soap.vndToForeginAsync(WebApplication1.ServiceReference1.vndToForeginRequest request) {
            return base.Channel.vndToForeginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.vndToForeginResponse> vndToForeginAsync(double vnd, string name) {
            WebApplication1.ServiceReference1.vndToForeginRequest inValue = new WebApplication1.ServiceReference1.vndToForeginRequest();
            inValue.Body = new WebApplication1.ServiceReference1.vndToForeginRequestBody();
            inValue.Body.vnd = vnd;
            inValue.Body.name = name;
            return ((WebApplication1.ServiceReference1.WebService1Soap)(this)).vndToForeginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.foreginToVNDResponse WebApplication1.ServiceReference1.WebService1Soap.foreginToVND(WebApplication1.ServiceReference1.foreginToVNDRequest request) {
            return base.Channel.foreginToVND(request);
        }
        
        public double foreginToVND(double foregin, string name) {
            WebApplication1.ServiceReference1.foreginToVNDRequest inValue = new WebApplication1.ServiceReference1.foreginToVNDRequest();
            inValue.Body = new WebApplication1.ServiceReference1.foreginToVNDRequestBody();
            inValue.Body.foregin = foregin;
            inValue.Body.name = name;
            WebApplication1.ServiceReference1.foreginToVNDResponse retVal = ((WebApplication1.ServiceReference1.WebService1Soap)(this)).foreginToVND(inValue);
            return retVal.Body.foreginToVNDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.foreginToVNDResponse> WebApplication1.ServiceReference1.WebService1Soap.foreginToVNDAsync(WebApplication1.ServiceReference1.foreginToVNDRequest request) {
            return base.Channel.foreginToVNDAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.foreginToVNDResponse> foreginToVNDAsync(double foregin, string name) {
            WebApplication1.ServiceReference1.foreginToVNDRequest inValue = new WebApplication1.ServiceReference1.foreginToVNDRequest();
            inValue.Body = new WebApplication1.ServiceReference1.foreginToVNDRequestBody();
            inValue.Body.foregin = foregin;
            inValue.Body.name = name;
            return ((WebApplication1.ServiceReference1.WebService1Soap)(this)).foreginToVNDAsync(inValue);
        }
    }
}
